package com.github.lemfi.adventofcode.year2024

import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test

class Day08Test {

    @Test
    fun star1() {
        Assertions.assertEquals(
            14, Day08.star1(
                """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""
            )
        )
    }

    @Test
    fun star21() {
        Assertions.assertEquals(
            9, Day08.star2(
                """T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........
"""
            )
        )
    }

    @Test
    fun star22() {
        Assertions.assertEquals(
            34, Day08.star2(
                """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""
            )
        )
    }
}