package com.github.lemfi.adventofcode.year2022

import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test

class Day23Test {

    @Test
    fun star1() {
        Assertions.assertEquals(
            110, Day23.star1(
                """..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
.............."""
            )
        )
    }

    @Test
    fun star2() {
        Assertions.assertEquals(
            20, Day23.star2(
                """..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
.............."""
            )
        )
    }
}